name: Train & Deploy Model

on:
  push:
    branches: ["main"]

jobs:

  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Train model
      run: python scripts/train.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          app/model.pkl
          results/metrics.json


  deploy:
    runs-on: ubuntu-latest
    needs: train

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y jq bc

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: artifacts

    - name: Read metric
      id: metric
      run: |
        VALUE=$(jq '.f1' results/metrics.json)
        echo "VALUE=$VALUE" >> $GITHUB_ENV

    - name: Compare metrics
      id: compare
      run: |
        OLD=${{ vars.BEST_F1 }}
        NEW=$VALUE

        echo "OLD=$OLD"
        echo "NEW=$NEW"

        if (( $(echo "$NEW > $OLD" | bc -l) )); then
          echo "deploy=true" >> $GITHUB_OUTPUT
        else
          echo "<YOUR_ROLL_NO>----Metric did not improve"
          echo "deploy=false" >> $GITHUB_OUTPUT
        fi

    - name: Stop if not improved
      if: steps.compare.outputs.deploy == 'false'
      run: exit 0

    - name: Docker login
      if: steps.compare.outputs.deploy == 'true'
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build image
      if: steps.compare.outputs.deploy == 'true'
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wine-api:latest .

    - name: Push image
      if: steps.compare.outputs.deploy == 'true'
      run: docker push ${{ secrets.DOCKER_USERNAME }}/wine-api:latest

    - name: Update BEST_F1
      if: steps.compare.outputs.deploy == 'true'
      run: |
        curl -X PATCH \
        -H "Authorization: token ${{ secrets.GH_PAT }}" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/repos/${{ github.repository }}/actions/variables/BEST_F1 \
        -d '{"name":"BEST_F1","value":"'"$VALUE"'"}'
